### PR TITLE
Major changes to word search

### PR DESCRIPTION
**Pull request by coffeecrank**
I changed how words + their context are found, also changed console output.
1. Context now consist of 2 words on the left and 2 words on the right.
2. Words are no more found in between <<>> tags and in code blocks within text.
3. Word search is implemented in pure Lua with Lua regex and some custom functions.
4. Added run.sh script to make sure both DocBook AND AsciiDoc work perfectly fine both locally and on Jenkins.
5. The way test works now is that run.sh is provided two parameters: path to Emender framework and path to docs, this is all that is needed and can be programmed both locally and on Jenkins to run automatically.

### CODE REVIEW

**Comment by tisnik** [comment]
LGTM so far. Are you going to merge it (after fixing merge conflicts)?

**Comment by coffeecrank** [comment]
@tisnik I gotta first fix the conflicts in Jenkins vs local runs. :) Seems to be some problem again that I didn't consider...
Also I don't have writing perms, only you have them. :) I might ask you to merge it later, when I verify everything.

**Comment by tisnik** [comment]
@coffeecrank I've sent you invitation, you should receive an e-mail from GitHub soon.

**Comment by coffeecrank** [comment]
@tisnik yay! :D Ty, I'll make sure to double-check everything both on Jenkins and locally and squash commits too.

**Comment by coffeecrank** [comment]
@tisnik this is all set (for some reason still can't merge it, it says no writing access).

**Pull request merged**
